---
apiVersion: batch/v1
kind: Job
metadata:
  name: demoapp-setup
spec:
  template:
    spec:
      containers:
        - name: setup
          image: demoapp:0.0.1
          command:
            - ./bin/setup-db
          envFrom:
            - configMapRef:
                name: demoapp-rails-env
            - secretRef:
                name: demoapp-rails-env
      restartPolicy: Never
  backoffLimit: 4
