---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demoapp.mysql-env.name" . }}
data:
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}