---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demoapp.rails-env.name" . }}
data:
  SECRET_KEY_BASE: {{ .Values.rails.secretKeyBase | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
